//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace Component.Model.br.com.maplink.services {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RouteProximitySoap", Namespace="http://webservices.maplink2.com.br")]
    public partial class RouteProximity : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getRouteProximityTotalsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRouteProximityTotalsBatchOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRouteProximityOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRouteProximityListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRouteProximitySummaryOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRouteProximityDescriptionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRouteProximityWithMapOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RouteProximity() {
            this.Url = global::Component.Model.Properties.Settings.Default.Component_Model_br_com_maplink_services_RouteProximity;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getRouteProximityTotalsCompletedEventHandler getRouteProximityTotalsCompleted;
        
        /// <remarks/>
        public event GetRouteProximityTotalsBatchCompletedEventHandler GetRouteProximityTotalsBatchCompleted;
        
        /// <remarks/>
        public event getRouteProximityCompletedEventHandler getRouteProximityCompleted;
        
        /// <remarks/>
        public event getRouteProximityListCompletedEventHandler getRouteProximityListCompleted;
        
        /// <remarks/>
        public event getRouteProximitySummaryCompletedEventHandler getRouteProximitySummaryCompleted;
        
        /// <remarks/>
        public event getRouteProximityDescriptionCompletedEventHandler getRouteProximityDescriptionCompleted;
        
        /// <remarks/>
        public event getRouteProximityWithMapCompletedEventHandler getRouteProximityWithMapCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.maplink2.com.br/getRouteProximityTotals", RequestNamespace="http://webservices.maplink2.com.br", ResponseNamespace="http://webservices.maplink2.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RouteTotals getRouteProximityTotals([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] RouteStop[] rs, RouteProximityOptions ro, string token) {
            object[] results = this.Invoke("getRouteProximityTotals", new object[] {
                        rs,
                        ro,
                        token});
            return ((RouteTotals)(results[0]));
        }
        
        /// <remarks/>
        public void getRouteProximityTotalsAsync(RouteStop[] rs, RouteProximityOptions ro, string token) {
            this.getRouteProximityTotalsAsync(rs, ro, token, null);
        }
        
        /// <remarks/>
        public void getRouteProximityTotalsAsync(RouteStop[] rs, RouteProximityOptions ro, string token, object userState) {
            if ((this.getRouteProximityTotalsOperationCompleted == null)) {
                this.getRouteProximityTotalsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRouteProximityTotalsOperationCompleted);
            }
            this.InvokeAsync("getRouteProximityTotals", new object[] {
                        rs,
                        ro,
                        token}, this.getRouteProximityTotalsOperationCompleted, userState);
        }
        
        private void OngetRouteProximityTotalsOperationCompleted(object arg) {
            if ((this.getRouteProximityTotalsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRouteProximityTotalsCompleted(this, new getRouteProximityTotalsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.maplink2.com.br/GetRouteProximityTotalsBatch", RequestNamespace="http://webservices.maplink2.com.br", ResponseNamespace="http://webservices.maplink2.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RouteTotals[] GetRouteProximityTotalsBatch([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] RouteArray[] ra, RouteProximityOptions ro, string token) {
            object[] results = this.Invoke("GetRouteProximityTotalsBatch", new object[] {
                        ra,
                        ro,
                        token});
            return ((RouteTotals[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRouteProximityTotalsBatchAsync(RouteArray[] ra, RouteProximityOptions ro, string token) {
            this.GetRouteProximityTotalsBatchAsync(ra, ro, token, null);
        }
        
        /// <remarks/>
        public void GetRouteProximityTotalsBatchAsync(RouteArray[] ra, RouteProximityOptions ro, string token, object userState) {
            if ((this.GetRouteProximityTotalsBatchOperationCompleted == null)) {
                this.GetRouteProximityTotalsBatchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRouteProximityTotalsBatchOperationCompleted);
            }
            this.InvokeAsync("GetRouteProximityTotalsBatch", new object[] {
                        ra,
                        ro,
                        token}, this.GetRouteProximityTotalsBatchOperationCompleted, userState);
        }
        
        private void OnGetRouteProximityTotalsBatchOperationCompleted(object arg) {
            if ((this.GetRouteProximityTotalsBatchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRouteProximityTotalsBatchCompleted(this, new GetRouteProximityTotalsBatchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.maplink2.com.br/getRouteProximity", RequestNamespace="http://webservices.maplink2.com.br", ResponseNamespace="http://webservices.maplink2.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RouteProximityInfo getRouteProximity([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] RouteStop[] rs, RouteProximityOptions ro, string token) {
            object[] results = this.Invoke("getRouteProximity", new object[] {
                        rs,
                        ro,
                        token});
            return ((RouteProximityInfo)(results[0]));
        }
        
        /// <remarks/>
        public void getRouteProximityAsync(RouteStop[] rs, RouteProximityOptions ro, string token) {
            this.getRouteProximityAsync(rs, ro, token, null);
        }
        
        /// <remarks/>
        public void getRouteProximityAsync(RouteStop[] rs, RouteProximityOptions ro, string token, object userState) {
            if ((this.getRouteProximityOperationCompleted == null)) {
                this.getRouteProximityOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRouteProximityOperationCompleted);
            }
            this.InvokeAsync("getRouteProximity", new object[] {
                        rs,
                        ro,
                        token}, this.getRouteProximityOperationCompleted, userState);
        }
        
        private void OngetRouteProximityOperationCompleted(object arg) {
            if ((this.getRouteProximityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRouteProximityCompleted(this, new getRouteProximityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.maplink2.com.br/getRouteProximityList", RequestNamespace="http://webservices.maplink2.com.br", ResponseNamespace="http://webservices.maplink2.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ProximityList[] getRouteProximityList([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] RouteStop[] rs, RouteProximityOptions ro, string token) {
            object[] results = this.Invoke("getRouteProximityList", new object[] {
                        rs,
                        ro,
                        token});
            return ((ProximityList[])(results[0]));
        }
        
        /// <remarks/>
        public void getRouteProximityListAsync(RouteStop[] rs, RouteProximityOptions ro, string token) {
            this.getRouteProximityListAsync(rs, ro, token, null);
        }
        
        /// <remarks/>
        public void getRouteProximityListAsync(RouteStop[] rs, RouteProximityOptions ro, string token, object userState) {
            if ((this.getRouteProximityListOperationCompleted == null)) {
                this.getRouteProximityListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRouteProximityListOperationCompleted);
            }
            this.InvokeAsync("getRouteProximityList", new object[] {
                        rs,
                        ro,
                        token}, this.getRouteProximityListOperationCompleted, userState);
        }
        
        private void OngetRouteProximityListOperationCompleted(object arg) {
            if ((this.getRouteProximityListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRouteProximityListCompleted(this, new getRouteProximityListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.maplink2.com.br/getRouteProximitySummary", RequestNamespace="http://webservices.maplink2.com.br", ResponseNamespace="http://webservices.maplink2.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RouteSummary[] getRouteProximitySummary([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] RouteStop[] rs, RouteProximityOptions ro, string token) {
            object[] results = this.Invoke("getRouteProximitySummary", new object[] {
                        rs,
                        ro,
                        token});
            return ((RouteSummary[])(results[0]));
        }
        
        /// <remarks/>
        public void getRouteProximitySummaryAsync(RouteStop[] rs, RouteProximityOptions ro, string token) {
            this.getRouteProximitySummaryAsync(rs, ro, token, null);
        }
        
        /// <remarks/>
        public void getRouteProximitySummaryAsync(RouteStop[] rs, RouteProximityOptions ro, string token, object userState) {
            if ((this.getRouteProximitySummaryOperationCompleted == null)) {
                this.getRouteProximitySummaryOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRouteProximitySummaryOperationCompleted);
            }
            this.InvokeAsync("getRouteProximitySummary", new object[] {
                        rs,
                        ro,
                        token}, this.getRouteProximitySummaryOperationCompleted, userState);
        }
        
        private void OngetRouteProximitySummaryOperationCompleted(object arg) {
            if ((this.getRouteProximitySummaryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRouteProximitySummaryCompleted(this, new getRouteProximitySummaryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.maplink2.com.br/getRouteProximityDescription", RequestNamespace="http://webservices.maplink2.com.br", ResponseNamespace="http://webservices.maplink2.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SegmentDescription[] getRouteProximityDescription([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] RouteStop[] rs, RouteProximityOptions ro, string token) {
            object[] results = this.Invoke("getRouteProximityDescription", new object[] {
                        rs,
                        ro,
                        token});
            return ((SegmentDescription[])(results[0]));
        }
        
        /// <remarks/>
        public void getRouteProximityDescriptionAsync(RouteStop[] rs, RouteProximityOptions ro, string token) {
            this.getRouteProximityDescriptionAsync(rs, ro, token, null);
        }
        
        /// <remarks/>
        public void getRouteProximityDescriptionAsync(RouteStop[] rs, RouteProximityOptions ro, string token, object userState) {
            if ((this.getRouteProximityDescriptionOperationCompleted == null)) {
                this.getRouteProximityDescriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRouteProximityDescriptionOperationCompleted);
            }
            this.InvokeAsync("getRouteProximityDescription", new object[] {
                        rs,
                        ro,
                        token}, this.getRouteProximityDescriptionOperationCompleted, userState);
        }
        
        private void OngetRouteProximityDescriptionOperationCompleted(object arg) {
            if ((this.getRouteProximityDescriptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRouteProximityDescriptionCompleted(this, new getRouteProximityDescriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.maplink2.com.br/getRouteProximityWithMap", RequestNamespace="http://webservices.maplink2.com.br", ResponseNamespace="http://webservices.maplink2.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RouteProximityInfo getRouteProximityWithMap([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] RouteStop[] rs, RouteProximityOptions ro, MapOptions mo, string token) {
            object[] results = this.Invoke("getRouteProximityWithMap", new object[] {
                        rs,
                        ro,
                        mo,
                        token});
            return ((RouteProximityInfo)(results[0]));
        }
        
        /// <remarks/>
        public void getRouteProximityWithMapAsync(RouteStop[] rs, RouteProximityOptions ro, MapOptions mo, string token) {
            this.getRouteProximityWithMapAsync(rs, ro, mo, token, null);
        }
        
        /// <remarks/>
        public void getRouteProximityWithMapAsync(RouteStop[] rs, RouteProximityOptions ro, MapOptions mo, string token, object userState) {
            if ((this.getRouteProximityWithMapOperationCompleted == null)) {
                this.getRouteProximityWithMapOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRouteProximityWithMapOperationCompleted);
            }
            this.InvokeAsync("getRouteProximityWithMap", new object[] {
                        rs,
                        ro,
                        mo,
                        token}, this.getRouteProximityWithMapOperationCompleted, userState);
        }
        
        private void OngetRouteProximityWithMapOperationCompleted(object arg) {
            if ((this.getRouteProximityWithMapCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRouteProximityWithMapCompleted(this, new getRouteProximityWithMapCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class RouteStop {
        
        private string descriptionField;
        
        private Point pointField;
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public Point point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class Point {
        
        private double xField;
        
        private double yField;
        
        /// <remarks/>
        public double x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        public double y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class MapSize {
        
        private int widthField;
        
        private int heightField;
        
        /// <remarks/>
        public int width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public int height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class MapOptions {
        
        private bool scaleBarField;
        
        private MapSize mapSizeField;
        
        /// <remarks/>
        public bool scaleBar {
            get {
                return this.scaleBarField;
            }
            set {
                this.scaleBarField = value;
            }
        }
        
        /// <remarks/>
        public MapSize mapSize {
            get {
                return this.mapSizeField;
            }
            set {
                this.mapSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class ProximityList {
        
        private int clientIDField;
        
        private string clientDetailsField;
        
        private Point pointField;
        
        /// <remarks/>
        public int clientID {
            get {
                return this.clientIDField;
            }
            set {
                this.clientIDField = value;
            }
        }
        
        /// <remarks/>
        public string clientDetails {
            get {
                return this.clientDetailsField;
            }
            set {
                this.clientDetailsField = value;
            }
        }
        
        /// <remarks/>
        public Point point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class RoadType {
        
        private double twoLaneHighwayField;
        
        private double secondLaneUnderConstructionField;
        
        private double oneLaneRoadwayField;
        
        private double pavingWorkInProgressField;
        
        private double dirtRoadField;
        
        private double roadwayInPoorConditionsField;
        
        private double ferryField;
        
        /// <remarks/>
        public double twoLaneHighway {
            get {
                return this.twoLaneHighwayField;
            }
            set {
                this.twoLaneHighwayField = value;
            }
        }
        
        /// <remarks/>
        public double secondLaneUnderConstruction {
            get {
                return this.secondLaneUnderConstructionField;
            }
            set {
                this.secondLaneUnderConstructionField = value;
            }
        }
        
        /// <remarks/>
        public double oneLaneRoadway {
            get {
                return this.oneLaneRoadwayField;
            }
            set {
                this.oneLaneRoadwayField = value;
            }
        }
        
        /// <remarks/>
        public double pavingWorkInProgress {
            get {
                return this.pavingWorkInProgressField;
            }
            set {
                this.pavingWorkInProgressField = value;
            }
        }
        
        /// <remarks/>
        public double dirtRoad {
            get {
                return this.dirtRoadField;
            }
            set {
                this.dirtRoadField = value;
            }
        }
        
        /// <remarks/>
        public double roadwayInPoorConditions {
            get {
                return this.roadwayInPoorConditionsField;
            }
            set {
                this.roadwayInPoorConditionsField = value;
            }
        }
        
        /// <remarks/>
        public double ferry {
            get {
                return this.ferryField;
            }
            set {
                this.ferryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class RouteSummary {
        
        private string descriptionField;
        
        private double distanceField;
        
        private Point pointField;
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public double distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        public Point point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class TollFeeDetails {
        
        private string nameField;
        
        private string directionField;
        
        private string addressField;
        
        private string concessionField;
        
        private string phoneField;
        
        private string stateField;
        
        private double priceField;
        
        private double pricePerAxleField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string concession {
            get {
                return this.concessionField;
            }
            set {
                this.concessionField = value;
            }
        }
        
        /// <remarks/>
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public double price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public double pricePerAxle {
            get {
                return this.pricePerAxleField;
            }
            set {
                this.pricePerAxleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class City {
        
        private string nameField;
        
        private string stateField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class POIDetails {
        
        private string clientIDField;
        
        private string nameField;
        
        private string addressInfoField;
        
        private string sourceField;
        
        private Point pointField;
        
        /// <remarks/>
        public string clientID {
            get {
                return this.clientIDField;
            }
            set {
                this.clientIDField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string addressInfo {
            get {
                return this.addressInfoField;
            }
            set {
                this.addressInfoField = value;
            }
        }
        
        /// <remarks/>
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public Point point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class SegmentDescription {
        
        private string commandField;
        
        private string descriptionField;
        
        private string poiRouteField;
        
        private POIDetails[] poiRouteDetailsField;
        
        private City cityField;
        
        private string tollFeeField;
        
        private TollFeeDetails tollFeeDetailsField;
        
        private string roadTypeField;
        
        private double distanceField;
        
        private double cumulativeDistanceField;
        
        private Point pointField;
        
        /// <remarks/>
        public string command {
            get {
                return this.commandField;
            }
            set {
                this.commandField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string poiRoute {
            get {
                return this.poiRouteField;
            }
            set {
                this.poiRouteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public POIDetails[] poiRouteDetails {
            get {
                return this.poiRouteDetailsField;
            }
            set {
                this.poiRouteDetailsField = value;
            }
        }
        
        /// <remarks/>
        public City city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string tollFee {
            get {
                return this.tollFeeField;
            }
            set {
                this.tollFeeField = value;
            }
        }
        
        /// <remarks/>
        public TollFeeDetails tollFeeDetails {
            get {
                return this.tollFeeDetailsField;
            }
            set {
                this.tollFeeDetailsField = value;
            }
        }
        
        /// <remarks/>
        public string roadType {
            get {
                return this.roadTypeField;
            }
            set {
                this.roadTypeField = value;
            }
        }
        
        /// <remarks/>
        public double distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        public double cumulativeDistance {
            get {
                return this.cumulativeDistanceField;
            }
            set {
                this.cumulativeDistanceField = value;
            }
        }
        
        /// <remarks/>
        public Point point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class Extent {
        
        private double xMinField;
        
        private double yMinField;
        
        private double xMaxField;
        
        private double yMaxField;
        
        /// <remarks/>
        public double XMin {
            get {
                return this.xMinField;
            }
            set {
                this.xMinField = value;
            }
        }
        
        /// <remarks/>
        public double YMin {
            get {
                return this.yMinField;
            }
            set {
                this.yMinField = value;
            }
        }
        
        /// <remarks/>
        public double XMax {
            get {
                return this.xMaxField;
            }
            set {
                this.xMaxField = value;
            }
        }
        
        /// <remarks/>
        public double YMax {
            get {
                return this.yMaxField;
            }
            set {
                this.yMaxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class MapInfo {
        
        private string urlField;
        
        private Extent extentField;
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public Extent extent {
            get {
                return this.extentField;
            }
            set {
                this.extentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class RouteProximityInfo {
        
        private string routeIdField;
        
        private MapInfo mapInfoField;
        
        private SegmentDescription[] segDescriptionField;
        
        private RouteTotals routeTotalsField;
        
        private RouteSummary[] routeSummaryField;
        
        private RoadType roadTypeField;
        
        private ProximityList[] proximityListField;
        
        /// <remarks/>
        public string routeId {
            get {
                return this.routeIdField;
            }
            set {
                this.routeIdField = value;
            }
        }
        
        /// <remarks/>
        public MapInfo MapInfo {
            get {
                return this.mapInfoField;
            }
            set {
                this.mapInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SegmentDescription[] segDescription {
            get {
                return this.segDescriptionField;
            }
            set {
                this.segDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public RouteTotals routeTotals {
            get {
                return this.routeTotalsField;
            }
            set {
                this.routeTotalsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RouteSummary[] routeSummary {
            get {
                return this.routeSummaryField;
            }
            set {
                this.routeSummaryField = value;
            }
        }
        
        /// <remarks/>
        public RoadType roadType {
            get {
                return this.roadTypeField;
            }
            set {
                this.roadTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ProximityList[] proximityList {
            get {
                return this.proximityListField;
            }
            set {
                this.proximityListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class RouteTotals {
        
        private double totalDistanceField;
        
        private string totalTimeField;
        
        private double totalFuelUsedField;
        
        private double totaltollFeeCostField;
        
        private double totalfuelCostField;
        
        private double totalCostField;
        
        private double taxiFare1Field;
        
        private double taxiFare2Field;
        
        /// <remarks/>
        public double totalDistance {
            get {
                return this.totalDistanceField;
            }
            set {
                this.totalDistanceField = value;
            }
        }
        
        /// <remarks/>
        public string totalTime {
            get {
                return this.totalTimeField;
            }
            set {
                this.totalTimeField = value;
            }
        }
        
        /// <remarks/>
        public double totalFuelUsed {
            get {
                return this.totalFuelUsedField;
            }
            set {
                this.totalFuelUsedField = value;
            }
        }
        
        /// <remarks/>
        public double totaltollFeeCost {
            get {
                return this.totaltollFeeCostField;
            }
            set {
                this.totaltollFeeCostField = value;
            }
        }
        
        /// <remarks/>
        public double totalfuelCost {
            get {
                return this.totalfuelCostField;
            }
            set {
                this.totalfuelCostField = value;
            }
        }
        
        /// <remarks/>
        public double totalCost {
            get {
                return this.totalCostField;
            }
            set {
                this.totalCostField = value;
            }
        }
        
        /// <remarks/>
        public double taxiFare1 {
            get {
                return this.taxiFare1Field;
            }
            set {
                this.taxiFare1Field = value;
            }
        }
        
        /// <remarks/>
        public double taxiFare2 {
            get {
                return this.taxiFare2Field;
            }
            set {
                this.taxiFare2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class RouteArray {
        
        private RouteStop originField;
        
        private RouteStop destField;
        
        /// <remarks/>
        public RouteStop Origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        public RouteStop Dest {
            get {
                return this.destField;
            }
            set {
                this.destField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class RouteLine {
        
        private int widthField;
        
        private string rGBField;
        
        private double transparencyField;
        
        /// <remarks/>
        public int width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public string RGB {
            get {
                return this.rGBField;
            }
            set {
                this.rGBField = value;
            }
        }
        
        /// <remarks/>
        public double transparency {
            get {
                return this.transparencyField;
            }
            set {
                this.transparencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class Vehicle {
        
        private int tankCapacityField;
        
        private float averageConsumptionField;
        
        private double fuelPriceField;
        
        private int averageSpeedField;
        
        private int tollFeeCatField;
        
        /// <remarks/>
        public int tankCapacity {
            get {
                return this.tankCapacityField;
            }
            set {
                this.tankCapacityField = value;
            }
        }
        
        /// <remarks/>
        public float averageConsumption {
            get {
                return this.averageConsumptionField;
            }
            set {
                this.averageConsumptionField = value;
            }
        }
        
        /// <remarks/>
        public double fuelPrice {
            get {
                return this.fuelPriceField;
            }
            set {
                this.fuelPriceField = value;
            }
        }
        
        /// <remarks/>
        public int averageSpeed {
            get {
                return this.averageSpeedField;
            }
            set {
                this.averageSpeedField = value;
            }
        }
        
        /// <remarks/>
        public int tollFeeCat {
            get {
                return this.tollFeeCatField;
            }
            set {
                this.tollFeeCatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class RouteDetails {
        
        private int descriptionTypeField;
        
        private int routeTypeField;
        
        private bool optimizeRouteField;
        
        private string[] poiRouteField;
        
        private string[] barriersListField;
        
        private Point[] barrierPointsField;
        
        /// <remarks/>
        public int descriptionType {
            get {
                return this.descriptionTypeField;
            }
            set {
                this.descriptionTypeField = value;
            }
        }
        
        /// <remarks/>
        public int routeType {
            get {
                return this.routeTypeField;
            }
            set {
                this.routeTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool optimizeRoute {
            get {
                return this.optimizeRouteField;
            }
            set {
                this.optimizeRouteField = value;
            }
        }
        
        /// <remarks/>
        public string[] poiRoute {
            get {
                return this.poiRouteField;
            }
            set {
                this.poiRouteField = value;
            }
        }
        
        /// <remarks/>
        public string[] barriersList {
            get {
                return this.barriersListField;
            }
            set {
                this.barriersListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Point[] barrierPoints {
            get {
                return this.barrierPointsField;
            }
            set {
                this.barrierPointsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class RouteProximityOptions {
        
        private string languageField;
        
        private RouteDetails routeDetailsField;
        
        private Vehicle vehicleField;
        
        private RouteLine[] routeLineField;
        
        private int radiusField;
        
        /// <remarks/>
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public RouteDetails routeDetails {
            get {
                return this.routeDetailsField;
            }
            set {
                this.routeDetailsField = value;
            }
        }
        
        /// <remarks/>
        public Vehicle vehicle {
            get {
                return this.vehicleField;
            }
            set {
                this.vehicleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RouteLine[] routeLine {
            get {
                return this.routeLineField;
            }
            set {
                this.routeLineField = value;
            }
        }
        
        /// <remarks/>
        public int radius {
            get {
                return this.radiusField;
            }
            set {
                this.radiusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getRouteProximityTotalsCompletedEventHandler(object sender, getRouteProximityTotalsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRouteProximityTotalsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRouteProximityTotalsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RouteTotals Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RouteTotals)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetRouteProximityTotalsBatchCompletedEventHandler(object sender, GetRouteProximityTotalsBatchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRouteProximityTotalsBatchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRouteProximityTotalsBatchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RouteTotals[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RouteTotals[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getRouteProximityCompletedEventHandler(object sender, getRouteProximityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRouteProximityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRouteProximityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RouteProximityInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RouteProximityInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getRouteProximityListCompletedEventHandler(object sender, getRouteProximityListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRouteProximityListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRouteProximityListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProximityList[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProximityList[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getRouteProximitySummaryCompletedEventHandler(object sender, getRouteProximitySummaryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRouteProximitySummaryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRouteProximitySummaryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RouteSummary[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RouteSummary[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getRouteProximityDescriptionCompletedEventHandler(object sender, getRouteProximityDescriptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRouteProximityDescriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRouteProximityDescriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SegmentDescription[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SegmentDescription[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getRouteProximityWithMapCompletedEventHandler(object sender, getRouteProximityWithMapCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRouteProximityWithMapCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRouteProximityWithMapCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RouteProximityInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RouteProximityInfo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591